name: Test linked issues
on:
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:
  check_pull_requests:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use the action
        uses: ramonmulia/test_linked_issue@v4
        id: check
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          exclude-branches: "release/**, dependabot/**"
      # Use the output from the `check` step
      - name: Get the output
        run: echo "Has linked issues? ${{ steps.check.outputs.linked_issues_count }}"
